#
# docker-compose.yml
# This file defines the services for a local development environment.
# Save this file as `docker-compose.yml` in the root directory.
#
version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    container_name: eprocurement-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: eprocurement-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - eprocurement_data:/var/lib/postgresql/data

volumes:
  eprocurement_data:
